export const LOG_IN = "LOG_IN";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAILURE = "LOG_IN_FAILURE";

export const LOG_OUT = "LOG_OUT";
export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS";
export const LOG_OUT_FAILURE = "LOG_OUT_FAILURE";

export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const CONFIRM_SIGNUP = "CONFIRM_SIGNUP";
export const CONFIRM_SIGNUP_SUCCESS = "CONFIRM_SIGNUP_SUCCESS";
export const CONFIRM_SIGNUP_FAILURE = "CONFIRM_SIGNUP_FAILURE";

export const CONFIRM_LOGIN = "CONFIRM_LOGIN";
export const CONFIRM_LOGIN_SUCCESS = "CONFIRM_LOGIN_SUCCESS";
export const CONFIRM_LOGIN_FAILURE = "CONFIRM_LOGIN_FAILURE";

export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";

export const FORGOT_PASSWORD_SUBMIT = "FORGOT_PASSWORD_SUBMIT";
export const FORGOT_PASSWORD_SUBMIT_SUCCESS = "FORGOT_PASSWORD_SUBMIT_SUCCESS";
export const FORGOT_PASSWORD_SUBMIT_FAILURE = "FORGOT_PASSWORD_SUBMIT_FAILURE";

export const RESEND_CONFIRM_CODE = "RESEND_CONFIRM_CODE";
export const RESEND_CONFIRM_CODE_FAILURE = "RESEND_CONFIRM_CODE_FAILURE";
export const RESEND_CONFIRM_CODE_SUCCESS = "RESEND_CONFIRM_CODE_SUCCESS";

export const AUTHENTICATE = "AUTHENTICATE";
export const AUTHENTICATE_FAILURE = "AUTHENTICATE_FAILURE";
export const AUTHENTICATE_SUCCESS = "AUTHENTICATE_SUCCESS";