export const GET_PATIENT = "GET_PATIENT";
export const GET_PATIENT_SUCCESS = "GET_PATIENT_SUCCESS";
export const GET_PATIENT_FAILURE = "GET_PATIENT_FAILURE";

export const REFRESH_PATIENT = "REFRESH_PATIENT";
export const REFRESH_PATIENT_SUCCESS = "REFRESH_PATIENT_SUCCESS";
export const REFRESH_PATIENT_FAILURE = "REFRESH_PATIENT_FAILURE";

export const GET_PATIENT_INFO = "GET_PATIENT_INFO";
export const GET_PATIENT_INFO_SUCCESS = "GET_PATIENT_INFO_SUCCESS";
export const GET_PATIENT_INFO_FAILURE = "GET_PATIENT_INFO_FAILURE";

export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";
export const GET_NOTIFICATION = "GET_NOTIFICATION";
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const GET_NOTIFICATION_FAILURE = "GET_NOTIFICATION_FAILURE";

export const UPDATE_LOCATION = "UPDATE_LOCATION";
export const GET_LOCATION = "GET_LOCATION";
export const GET_LOCATION_SUCCESS = "GET_LOCATION_SUCCESS";
export const GET_LOCATION_FAILURE = "GET_LOCATION_FAILURE";
